(function(){
  const A="assets/pruefung/";

  const PRUEFUNG_WORLDS = [
    {name:"Mikroskop & Zelle", emoji:"🔬", cls:"w0", desc:"Diagramme, Heuaufguss, Pflanzenzelle"},
    {name:"Blüte & Bestäubung", emoji:"🌸", cls:"w1", desc:"Fruchtblatt, Narbe, Wind- und Tierbestäubung"},
    {name:"Labor & Experiment", emoji:"🧪", cls:"w2", desc:"Laborgeräte, Messung, Variablenkontrolle"},
    {name:"Reiz, Blut & Tiere", emoji:"🫀", cls:"w3", desc:"Reiz-Reaktion, Blutkreislauf, Bestimmungsschlüssel"},
    {name:"Bewerten & Informatik", emoji:"💻", cls:"w4", desc:"Sach-/Wertaussagen, Objekt- und Klassendiagramme"}
  ];

  const PRUEFUNG_Q = [
  /* ============ WELT 0: Mikroskop & Zelle ============ */
  {w:0,ab:1,type:"sort",op:"Auswerten",q:"Werte das Heuaufguss-Diagramm aus: Ordne jede Aussage richtig zu.",
    media:{src:A+"heuaufguss_diagramm.png",alt:"Liniendiagramm zur Anzahl von Bakterien, Heutierchen, Pantoffeltierchen und Amöben im Heuaufguss über 30 Tage.",caption:"Diagramm: Lebewesen in einem Heuaufguss über 30 Tage"},
    cats:["Richtig belegbar","Falsch","Nicht entscheidbar"],
    items:[
      {t:"Die Zahl der Bakterien steigt zu Beginn stark an und nimmt danach wieder ab.",cat:0},
      {t:"Mit einem anderen Mikroskop hätte man mehr Lebewesen entdeckt.",cat:2},
      {t:"An Tag 20 leben mehr Amöben als Pantoffeltierchen im Heuaufguss.",cat:1},
      {t:"Es gibt einen Zeitpunkt, zu dem gleich viele Heutierchen wie Pantoffeltierchen leben.",cat:0}
    ],
    tip:"Nur Aussagen, die direkt aus den Messwerten folgen, sind richtig belegbar.",
    erkl:"Richtig belegbar sind der Bakterienverlauf und der Schnittpunkt von Heutierchen und Pantoffeltierchen. Das andere Mikroskop wurde nicht getestet. An Tag 20 liegen Pantoffeltierchen über Amöben."},
  {w:0,ab:1,type:"mc",op:"Ablesen",q:"Welche Lebewesen erreichen im Diagramm den höchsten Maximalwert?",
    media:{src:A+"heuaufguss_diagramm.png",alt:"Heuaufguss-Diagramm mit vier Linien.",caption:"Achte auf den höchsten Punkt der Linien."},
    a:["Bakterien","Heutierchen","Pantoffeltierchen","Amöben"],c:0,
    tip:"Die höchste Kurve steigt in den ersten Tagen sehr stark an.",
    erkl:"Die Bakterien erreichen mit deutlich über 500 Lebewesen den höchsten Maximalwert."},
  {w:0,ab:1,type:"label",op:"Benennen",q:"Markiere zwei Zellbestandteile, an denen man eine pflanzliche Zelle erkennt.",
    media:{src:A+"pflanzenzelle.png",alt:"Vereinfachte Zeichnung einer pflanzlichen Zelle mit Zellwand, Chloroplasten und großer Vakuole.",caption:"Pflanzliche Zelle im Lichtmikroskop"},
    slots:[{n:1,term:"Chloroplast",x:73,y:14},{n:2,term:"Vakuole",x:54,y:43}],
    tip:"Pflanzliche Zellen enthalten grüne Chloroplasten und oft eine große Vakuole.",
    erkl:"Chloroplasten und die große Vakuole sind typische Merkmale pflanzlicher Zellen. Eine Tierzelle besitzt diese Bestandteile nicht in dieser Form."},
  {w:0,ab:1,type:"sort",op:"Zuordnen",q:"Ordne die Zellbestandteile richtig zu.",
    cats:["Pflanzlich typisch","Bei Tier- und Pflanzenzellen"],
    items:[{t:"Chloroplast",cat:0},{t:"große Vakuole",cat:0},{t:"Zellkern",cat:1},{t:"Zellmembran",cat:1},{t:"Zellplasma",cat:1}],
    tip:"Die Frage sucht nicht nach allen Bestandteilen, sondern nach Unterscheidungsmerkmalen.",
    erkl:"Chloroplasten und große Vakuole helfen, die Pflanzenzelle zu erkennen. Zellkern, Zellmembran und Zellplasma kommen bei beiden Zelltypen vor."},
  {w:0,ab:2,type:"explain",op:"Erklären",q:"Erkläre, warum ein Lichtmikroskop für den Heuaufguss nötig ist.",
    media:{src:A+"mikroskop_lebewesen.png",alt:"Runder Blick durchs Mikroskop mit verschiedenen Kleinstlebewesen.",caption:"Mikroskopischer Blick in einen Heuaufguss"},
    claim:"Im Heuaufguss befinden sich Kleinstlebewesen, die mit bloßem Auge nicht sicher erkennbar sind.",
    parts:[
      {q:"Warum reicht das bloße Auge nicht aus?",a:["Die Lebewesen sind sehr klein und werden erst durch starke Vergrößerung sichtbar","Das Mikroskop färbt alle Lebewesen automatisch","Eine Lupe zählt die Lebewesen selbstständig"],c:0},
      {q:"Welche Angabe macht die Untersuchung vergleichbar?",a:["Dass täglich ein Tropfen untersucht und die Anzahl notiert wurde","Dass das Glas schön aussah","Dass nur am letzten Tag gemessen wurde"],c:0}
    ],
    tip:"Denke an Vergrößerung und gleiche Messweise.",
    erkl:"Ein Lichtmikroskop macht Kleinstlebewesen sichtbar. Vergleichbar werden die Werte, weil regelmäßig nach derselben Messidee gezählt wurde."},
  {w:0,ab:2,type:"explain",op:"Begründen",q:"Warum darfst du aus dem Diagramm nicht folgern: 'Ein anderes Mikroskop hätte mehr Lebewesen gezeigt'?",
    claim:"Das Diagramm zeigt Messwerte aus genau dieser Untersuchung.",
    parts:[
      {q:"Was fehlt für diese Schlussfolgerung?",a:["Ein Vergleich mit einem anderen Mikroskop","Eine Beschriftung der y-Achse","Die Namen der Lebewesen"],c:0},
      {q:"Wie wird die Aussage daher bewertet?",a:["Nicht entscheidbar mit den vorliegenden Messwerten","Sicher richtig","Sicher falsch, weil andere Mikroskope nie anders messen"],c:0}
    ],
    tip:"Unterscheide Messwert und Vermutung.",
    erkl:"Die Messwerte zeigen nur diese Untersuchung. Ohne Vergleichsmessung mit einem anderen Mikroskop ist die Aussage nicht entscheidbar."},
  {w:0,ab:3,type:"judge",op:"Beurteilen",boss:true,q:"Beurteile eine Auswertung des Heuaufguss-Diagramms.",
    scenario:"Eine Schülerin schreibt: 'An Tag 20 gibt es mehr Amöben als Pantoffeltierchen, weil die Amöbenkurve später ansteigt.'",
    verdict:{q:"Ist diese Aussage zum Tag 20 fachlich richtig?",a:["Nein, sie ist falsch","Ja, sie ist richtig"],c:0},
    reason:{q:"Wähle die passenden Begründungen:",a:[
      "Am Tag 20 liegt die Kurve der Pantoffeltierchen über der Amöbenkurve",
      "Ein späterer Anstieg reicht nicht aus; man muss den Wert am genannten Tag ablesen",
      "Amöben sind immer häufiger als Pantoffeltierchen",
      "Das Diagramm enthält keine Zeitachse"],correct:[0,1]},
    tip:"Die Begründung muss zum konkreten Tag passen.",
    erkl:"Die Aussage ist falsch: Am Tag 20 zeigt das Diagramm mehr Pantoffeltierchen als Amöben. Entscheidend ist der abgelesene Wert am genannten Tag."},

  /* ============ WELT 1: Blüte & Bestäubung ============ */
  {w:1,ab:1,type:"mc",op:"Benennen",q:"Welcher Fachbegriff bezeichnet die klebrige Empfangsfläche des Fruchtblatts?",
    media:{src:A+"fruchtblaetter.png",alt:"Zwei Fruchtblätter A und B; bei B ist die Narbe verästelt.",caption:"Fruchtblätter zweier Pflanzenarten"},
    a:["Narbe","Pollen","Kelchblatt","Sprossachse"],c:0,
    tip:"Dort landen die Pollenkörner.",
    erkl:"Die Narbe ist die Empfangsfläche des Fruchtblatts, auf der Pollenkörner haften bleiben."},
  {w:1,ab:1,type:"compare",op:"Vergleichen",q:"Vergleiche die beiden Fruchtblätter A und B.",
    media:{src:A+"fruchtblaetter.png",alt:"Fruchtblatt A mit kleiner Narbe und Fruchtblatt B mit verästelter Narbe.",caption:"Vergleich der Narbenstrukturen"},
    left:"Nur A",midLabel:"Beide",right:"Nur B",
    items:[{t:"besitzt ein Fruchtblatt",cat:1},{t:"trägt Pollenkörner auf der Narbe",cat:1},{t:"hat eine stark verästelte Narbe",cat:2},{t:"zeigt die größere Narbenoberfläche",cat:2},{t:"hat die eher kompakte Narbe",cat:0}],
    tip:"Suche zuerst Gemeinsamkeiten, dann die auffällige Verzweigung.",
    erkl:"Beide Abbildungen zeigen Fruchtblätter mit Pollenkörnern. B besitzt eine verästelte Narbe und dadurch die größere Oberfläche."},
  {w:1,ab:2,type:"explain",op:"Ableiten",q:"Leite aus der Abbildung ab, welche Pflanze eher an Windbestäubung angepasst ist.",
    media:{src:A+"fruchtblaetter.png",alt:"Fruchtblätter A und B mit unterschiedlich gebauter Narbe.",caption:"Welche Narbe fängt Pollen aus der Luft besser ab?"},
    claim:"Windbestäubung ist ungezielt: Pollenkörner werden mit der Luft verteilt.",
    parts:[
      {q:"Welche Pflanze ist eher angepasst?",a:["Pflanze B","Pflanze A","Beide gleich, weil beide Fruchtblätter haben"],c:0},
      {q:"Welche Begründung passt?",a:["Die verästelte Narbe vergrößert die Oberfläche und kann Pollen aus der Luft wahrscheinlicher auffangen","Die glatte Narbe ist schwerer und deshalb besser","Windbestäubung braucht keine Narbe"],c:0}
    ],
    tip:"Mehr Oberfläche erhöht die Trefferchance.",
    erkl:"Pflanze B ist eher an Windbestäubung angepasst: Die verästelte Narbe besitzt eine größere Oberfläche und kann Pollen aus der Luft besser auffangen."},
  {w:1,ab:1,type:"sort",op:"Zuordnen",q:"Ordne typische Merkmale der Wind- und Tierbestäubung zu.",
    cats:["Windbestäubung","Tierbestäubung"],
    items:[{t:"viele leichte Pollen",cat:0},{t:"ungezielte Verteilung",cat:0},{t:"große oder verästelte Narben",cat:0},{t:"auffällige Blüten",cat:1},{t:"Duft und Nektar",cat:1},{t:"gezielter Besuch von Blüte zu Blüte",cat:1}],
    tip:"Wind verteilt breit, Tiere besuchen gezielter.",
    erkl:"Windbestäubung setzt auf viele leichte Pollen und große Fangflächen. Tierbestäubung lockt Tiere mit Farbe, Duft und Nektar an."},
  {w:1,ab:2,type:"explain",op:"Erklären",q:"Erkläre das Prinzip der Oberflächenvergrößerung am Beispiel der Narbe.",
    claim:"Die Narbe von Pflanze B ist mehrfach verästelt.",
    parts:[
      {q:"Was bewirkt die Verästelung?",a:["Sie vergrößert die Oberfläche","Sie verkleinert die Kontaktfläche","Sie ersetzt die Pollenkörner"],c:0},
      {q:"Warum ist das bei Windbestäubung nützlich?",a:["Die Chance steigt, dass Pollen aus der Luft hängen bleiben","Die Pflanze braucht dann kein Fruchtblatt","Pollen werden dadurch schwerer"],c:0}
    ],
    tip:"Wie bei Lungenbläschen oder Darmzotten: mehr Fläche, mehr Austausch oder Kontakt.",
    erkl:"Verzweigungen vergrößern die Oberfläche. Bei Windbestäubung erhöht das die Wahrscheinlichkeit, Pollen aus der Luft aufzufangen."},
  {w:1,ab:3,type:"judge",op:"Beurteilen",boss:true,q:"Beurteile eine Begründung zur Bestäubung.",
    scenario:"Ein Schüler sagt: 'Pflanze A ist windbestäubt, weil ihre Narbe einfacher gebaut ist und Pollen dann schneller vorbeifliegen.'",
    verdict:{q:"Ist diese Begründung tragfähig?",a:["Nein","Ja"],c:0},
    reason:{q:"Wähle die passenden Begründungen:",a:[
      "Bei Windbestäubung ist eine größere Fangfläche vorteilhaft",
      "Die verästelte Narbe von B bietet mehr Oberfläche für Pollen",
      "Eine einfache Narbe ist immer besser für Windbestäubung",
      "Pollen müssen möglichst schnell vorbeifliegen, damit Bestäubung gelingt"],correct:[0,1]},
    tip:"Prüfe, ob die Begründung die Trefferwahrscheinlichkeit erhöht.",
    erkl:"Die Begründung ist nicht tragfähig. Eher Pflanze B passt zur Windbestäubung, weil die verästelte Narbe eine größere Oberfläche bietet."},

  /* ============ WELT 2: Labor & Experiment ============ */
  {w:2,ab:1,type:"label",op:"Benennen",q:"Benenne die drei abgebildeten Laborgeräte.",
    media:{src:A+"laborgeraete.png",alt:"Drei Laborgeräte A, B und C: Becherglas, Erlenmeyerkolben und Messzylinder.",caption:"Laborgeräte aus der Beispielprüfung"},
    slots:[{n:1,term:"Becherglas",x:17,y:15},{n:2,term:"Erlenmeyerkolben",x:50,y:15},{n:3,term:"Messzylinder",x:83,y:15}],
    tip:"C hat die feinste Skala.",
    erkl:"A ist das Becherglas, B der Erlenmeyerkolben und C der Messzylinder."},
  {w:2,ab:1,type:"mc",op:"Auswählen",q:"Welches Gefäß ist für genaues Abmessen von 50 ml Wasser am besten geeignet?",
    media:{src:A+"laborgeraete.png",alt:"Becherglas, Erlenmeyerkolben und Messzylinder.",caption:"Welches Gerät misst Volumen am genauesten?"},
    a:["Messzylinder","Becherglas","Erlenmeyerkolben","Lupe"],c:0,
    tip:"Achte auf die feine Skala.",
    erkl:"Der Messzylinder ist wegen seiner feinen Skala am besten zum genauen Abmessen eines Volumens geeignet."},
  {w:2,ab:1,type:"sort",op:"Zuordnen",q:"Ordne die Laborgeräte ihren typischen Funktionen zu.",
    cats:["Genau messen","Gefäß / grob abmessen","Nicht passend"],
    items:[{t:"Messzylinder",cat:0},{t:"Becherglas",cat:1},{t:"Erlenmeyerkolben",cat:1},{t:"Thermometer zum Volumenmessen",cat:2},{t:"Waage zum Volumenmessen",cat:2}],
    tip:"Volumen in ml misst man mit einer Skala am Gefäß.",
    erkl:"Der Messzylinder misst Volumen genau. Becherglas und Erlenmeyerkolben sind Gefäße und messen nur grob. Thermometer und Waage messen andere Größen."},
  {w:2,ab:2,type:"sort",op:"Planen",q:"Für Körper 4 soll nur der Einfluss der Masse untersucht werden. Ordne die Angaben.",
    cats:["Muss gleich bleiben","Darf verändert werden"],
    items:[{t:"Volumen: 10 ml",cat:0},{t:"Form möglichst gleich",cat:0},{t:"Material / Versuchsaufbau",cat:0},{t:"Masse: z. B. 30 g",cat:1}],
    tip:"Nur eine Größe darf verändert werden.",
    erkl:"Um den Einfluss der Masse zu prüfen, wird nur die Masse verändert. Volumen, Form und Versuchsbedingungen bleiben gleich."},
  {w:2,ab:2,type:"explain",op:"Erklären",q:"Erkläre, warum man bei einem Experiment nur eine Variable verändert.",
    claim:"Eine Gruppe will herausfinden, ob die Masse die Sinkdauer eines Körpers beeinflusst.",
    parts:[
      {q:"Warum darf nicht gleichzeitig auch das Volumen geändert werden?",a:["Sonst weiß man nicht, ob Masse oder Volumen die Sinkdauer verändert hat","Dann dauert der Versuch zu lange","Dann ist das Wasser zu sauber"],c:0},
      {q:"Wie nennt man die Größen, die gleich bleiben?",a:["Kontrollierte Bedingungen","Zufallswerte","Pollenmerkmale"],c:0}
    ],
    tip:"Eindeutige Ursache statt Misch-Effekt.",
    erkl:"Nur die untersuchte Variable wird verändert. Alle anderen Bedingungen bleiben konstant, damit die Ursache der Wirkung eindeutig geprüft wird."},
  {w:2,ab:3,type:"judge",op:"Bewerten",boss:true,q:"Bewerte einen Versuchsplan zum Sinkexperiment.",
    scenario:"Körper 4 soll 30 g wiegen, aber zusätzlich ein größeres Volumen und eine ganz andere Form haben.",
    verdict:{q:"Eignet sich dieser Körper, um nur den Einfluss der Masse zu untersuchen?",a:["Nein","Ja"],c:0},
    reason:{q:"Wähle die passenden Begründungen:",a:[
      "Es werden mehrere Größen gleichzeitig verändert",
      "Der Einfluss der Masse kann nicht eindeutig erkannt werden",
      "Das Volumen muss sich immer ändern, wenn die Masse untersucht wird",
      "Eine andere Form verbessert automatisch die Vergleichbarkeit"],correct:[0,1]},
    tip:"Vergleichbarkeit ist der Kern.",
    erkl:"Der Plan ist ungeeignet, weil Masse, Volumen und Form gleichzeitig verändert werden. So bleibt unklar, welche Größe die Sinkdauer beeinflusst."},

  /* ============ WELT 3: Reiz, Blut & Tiere ============ */
  {w:3,ab:1,type:"order",op:"Ordnen",q:"Vervollständige die Reiz-Reaktions-Kette beim Blinzeln im Sonnenlicht.",
    media:{src:A+"reizreaktionskette.png",alt:"Schematische Reiz-Reaktions-Kette mit Lichtsituation, Auge, Gehirn, Nerven und Augenlidmuskeln.",caption:"Roland blinzelt im hellen Sonnenlicht."},
    items:["Reiz: helles Licht","Sinnesorgan: Auge","Weiterleitung der Informationen über Nerven","Verarbeitung im Gehirn","Weiterleitung über Nerven","Effektororgan: Muskeln im Augenlid","Reaktion: Augen schließen"],
    tip:"Vom Reiz geht es über Sinnesorgan und Gehirn zur Reaktion.",
    erkl:"Die Kette lautet: helles Licht → Auge → Nerven → Gehirn → Nerven → Muskeln im Augenlid → Augen schließen."},
  {w:3,ab:1,type:"label",op:"Beschriften",q:"Beschrifte die fehlenden Blutgefäße im Blutkreislauf.",
    media:{src:A+"blutkreislauf.png",alt:"Schema eines Teils des menschlichen Blutkreislaufs mit Herz, Körper- und Lungenkreislauf.",caption:"Wortfeld: Lungenvene, Lungenkapillaren, Körperarterie, Lungenarterie"},
    slots:[{n:1,term:"Lungenarterie",x:24,y:14},{n:2,term:"Lungenkapillaren",x:73,y:26},{n:3,term:"Lungenvene",x:82,y:42},{n:4,term:"Körperarterie",x:38,y:70}],
    tip:"Arterien führen vom Herzen weg, Venen zum Herzen hin.",
    erkl:"Zu ergänzen sind Lungenarterie, Lungenkapillaren, Lungenvene und Körperarterie. Körpervene und Körperkapillaren sind bereits angegeben."},
  {w:3,ab:2,type:"explain",op:"Erklären",q:"Erkläre die Aufgabe des Blutkreislaufs.",
    claim:"Das Herz pumpt Blut durch Körper- und Lungenkreislauf.",
    parts:[
      {q:"Warum braucht der Körper diesen Transport?",a:["Zellen werden mit Sauerstoff und Nährstoffen versorgt und Stoffe werden abtransportiert","Damit Knochen härter werden","Damit die Haut grün wird"],c:0},
      {q:"Welche Station gehört zum Gasaustausch?",a:["Lungenkapillaren","Magen","Blütennarbe"],c:0}
    ],
    tip:"Denke an Versorgung der Zellen.",
    erkl:"Der Blutkreislauf versorgt Zellen mit Sauerstoff und Nährstoffen. In den Lungenkapillaren findet der Gasaustausch statt."},
  {w:3,ab:1,type:"sort",op:"Bestimmen",q:"Bestimme die Amphibien anhand der Abbildungen.",
    media:{src:A+"amphibien_bestimmung.png",alt:"Drei Amphibien: Erdkröte, Grasfrosch und Kammmolch.",caption:"Amphibien 1 bis 3 aus der Beispielprüfung"},
    cats:["Amphibium 1","Amphibium 2","Amphibium 3"],
    items:[{t:"Erdkröte",cat:0},{t:"Grasfrosch",cat:1},{t:"Kammmolch",cat:2}],
    tip:"Warzige Haut passt zur Erdkröte; der Molch besitzt einen Schwanz.",
    erkl:"Amphibium 1 ist die Erdkröte, Amphibium 2 der Grasfrosch und Amphibium 3 der Kammmolch."},
  {w:3,ab:2,type:"order",op:"Anwenden",q:"Nutze den Bestimmungsschlüssel: Wie bestimmst du Amphibium 3?",
    media:{src:A+"amphibium_kammmolch.png",alt:"Molch mit seitlich abgeplattetem Schwanz und Rückenkamm.",caption:"Amphibium 3"},
    items:["Tier mit Schwanz","Schwanz seitlich abgeplattet","Rücken mit Rückenkamm","Kammmolch"],
    tip:"Folge den Merkmalen Schritt für Schritt.",
    erkl:"Der Bestimmungspfad lautet: Tier mit Schwanz → seitlich abgeplatteter Schwanz → Rücken mit Rückenkamm → Kammmolch."},
  {w:3,ab:3,type:"judge",op:"Beurteilen",boss:true,q:"Beurteile eine Artbestimmung.",
    scenario:"Jemand bestimmt Amphibium 1 als Grasfrosch, weil es keinen Schwanz hat.",
    verdict:{q:"Reicht diese Begründung aus?",a:["Nein","Ja"],c:0},
    reason:{q:"Wähle die passenden Begründungen:",a:[
      "Ohne Schwanz führt der Schlüssel weiter zu Merkmalen der Haut",
      "Die warzige Haut spricht für Erdkröte",
      "Alle schwanzlosen Amphibien sind Grasfrösche",
      "Für Bestimmungsschlüssel ist nur die Körpergröße wichtig"],correct:[0,1]},
    tip:"Ein Bestimmungsschritt reicht oft nicht.",
    erkl:"Die Begründung reicht nicht. Bei schwanzlosen Tieren muss weiter geprüft werden: warzige Haut führt zur Erdkröte."},

  /* ============ WELT 4: Bewerten & Informatik ============ */
  {w:4,ab:1,type:"sort",op:"Unterscheiden",q:"Ordne die Aussagen zum Skigebiet als beschreibend (S) oder bewertend (W).",
    cats:["Beschreibend (S)","Bewertend (W)"],
    items:[
      {t:"Je größer das Skigebiet ist, desto mehr Touristen können dort Ski fahren.",cat:0},
      {t:"Naturschutz ist wichtiger als das Vergnügen beim Skifahren.",cat:1},
      {t:"Durch den Ausbau können Verkehr und Lärmbelastung zunehmen.",cat:0},
      {t:"Die Einnahmen rechtfertigen die Beeinträchtigung der Schneehühner.",cat:1}
    ],
    tip:"Beschreibend ist überprüfbar; bewertend enthält eine Wertung.",
    erkl:"Beschreibende Aussagen stellen überprüfbare Zusammenhänge dar. Bewertende Aussagen wägen Werte ab, z. B. Naturschutz, Vergnügen oder Einnahmen."},
  {w:4,ab:2,type:"explain",op:"Begründen",q:"Begründe, warum eine Aussage bewertend ist.",
    claim:"'Naturschutz ist wichtiger als das Vergnügen beim Skifahren.'",
    parts:[
      {q:"Warum ist das eine bewertende Aussage?",a:["Sie gewichtet Werte und ist Ansichtssache","Sie misst eine Temperatur","Sie beschreibt nur eine gezählte Tierart"],c:0},
      {q:"Welche Gegenprobe passt?",a:["Man kann nicht allein durch Messen entscheiden, welcher Wert wichtiger ist","Man kann sie mit einem Messzylinder prüfen","Sie steht immer als Zahl im Diagramm"],c:0}
    ],
    tip:"Achte auf Wörter wie wichtiger, besser, gerechtfertigt.",
    erkl:"Die Aussage ist bewertend, weil sie Werte gegeneinander abwägt. Ob Naturschutz wichtiger ist, ist eine begründete Bewertung, kein reiner Messwert."},
  {w:4,ab:1,type:"mc",op:"Auswählen",q:"Was ist KREIS in der Informatik-Aufgabe?",
    media:{src:A+"informatik_k1_klassenkarte.png",alt:"Koordinatensystem mit Kreis k1 und Klassenkarte KREIS.",caption:"Objekt k1 und Klasse KREIS"},
    a:["Eine Klasse als Vorlage","Ein einzelnes Objekt","Ein Attributwert","Eine Messgröße"],c:0,
    tip:"Groß geschrieben ist hier die Vorlage.",
    erkl:"KREIS ist die Klasse, also die Vorlage. k1 ist ein konkretes Objekt dieser Klasse."},
  {w:4,ab:1,type:"sort",op:"Zuordnen",q:"Ordne Bestandteile der Klassenkarte KREIS zu.",
    media:{src:A+"informatik_k1_klassenkarte.png",alt:"Klassenkarte KREIS mit Attributen und Methoden.",caption:"Attribute stehen oben, Methoden unten."},
    cats:["Attribut","Methode","Objekt"],
    items:[{t:"mittelpunktX",cat:0},{t:"radius",cat:0},{t:"füllfarbe",cat:0},{t:"radiusSetzen(radiusNeu)",cat:1},{t:"verschiebenUm(x, y)",cat:1},{t:"k1",cat:2}],
    tip:"Methoden erkennt man an Klammern.",
    erkl:"Attribute sind Eigenschaften wie radius oder füllfarbe. Methoden sind Aktionen mit Klammern. k1 ist das konkrete Objekt."},
  {w:4,ab:2,type:"sort",op:"Zeichnen",q:"Welche Einträge gehören in die Objektkarte von k1?",
    media:{src:A+"informatik_k1_klassenkarte.png",alt:"Kreis k1 im Koordinatensystem mit Klassenkarte.",caption:"Lies Mittelpunkt, Radius und Farbe ab."},
    cats:["Gehört in die Objektkarte","Gehört nicht hinein"],
    items:[{t:"k1: KREIS",cat:0},{t:"mittelpunktX = 5",cat:0},{t:"mittelpunktY = 6",cat:0},{t:"radius = 3",cat:0},{t:"füllfarbe = grau",cat:0},{t:"alle Methoden der Klasse abschreiben",cat:1}],
    tip:"Eine Objektkarte beschreibt den Zustand eines konkreten Objekts.",
    erkl:"Die Objektkarte lautet: k1: KREIS, mittelpunktX = 5, mittelpunktY = 6, radius = 3, füllfarbe = grau. Methoden gehören in die Klassenkarte."},
  {w:4,ab:2,type:"sort",op:"Formalisieren",q:"Welche Methodenaufrufe erzeugen aus k2 die gezeigte Sichel?",
    media:{src:A+"informatik_k2_sichel.png",alt:"Koordinatensystem mit grauer Sichel und Kreis k2.",caption:"k2 wurde gegenüber k1 verändert."},
    cats:["Notwendig","Nicht passend"],
    items:[{t:"k2.verschiebenUm(3, 0)",cat:0},{t:"k2.radiusSetzen(4)",cat:0},{t:"k2.füllfarbeSetzen(weiß)",cat:0},{t:"k2.mittelpunktSetzen(0, 0)",cat:1},{t:"k2.nachHintenSetzen()",cat:1}],
    tip:"Vergleiche Position, Größe und Farbe.",
    erkl:"Notwendig sind k2.verschiebenUm(3, 0), k2.radiusSetzen(4) und k2.füllfarbeSetzen(weiß)."},
  {w:4,ab:3,type:"judge",op:"Beurteilen",boss:true,q:"Beurteile ein Klassendiagramm zur Gruppierung.",
    scenario:"Nach dem Gruppieren entsteht ein Objekt der Klasse GRUPPE, das Kreis-Objekte enthält.",
    verdict:{q:"Welche Beziehung passt im Klassendiagramm?",a:["GRUPPE enthält KREIS","KREIS enthält GRUPPE"],c:0},
    reason:{q:"Wähle die passenden Begründungen:",a:[
      "Die Gruppe besteht aus den markierten Kreis-Objekten",
      "Die Enthält-Beziehung zeigt vom Ganzen zu den enthaltenen Teilen",
      "Jeder Kreis besteht aus mehreren Gruppen",
      "Attribute müssen in diesem Klassendiagramm vollständig eingetragen werden"],correct:[0,1]},
    tip:"Eine Gruppe ist das Ganze, die Kreise sind Teile.",
    erkl:"Geeignet ist: GRUPPE enthält KREIS. Die Gruppe ist das Ganze; die Kreis-Objekte sind enthaltene Teile."}
  ];

  WORLDS.splice(0,WORLDS.length,...PRUEFUNG_WORLDS);
  Q.splice(0,Q.length,...PRUEFUNG_Q);
  if(typeof renderMap==="function") renderMap();
})();
